# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/XLINIX Projects/GP/better group project/CSE320-Project-Files/source files/constraints.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]
