set_property PACKAGE_PIN L18 [get_ports {cathode[6]}]
set_property PACKAGE_PIN T11 [get_ports {cathode[5]}]
set_property PACKAGE_PIN P15 [get_ports {cathode[4]}]
set_property PACKAGE_PIN K13 [get_ports {cathode[3]}]
set_property PACKAGE_PIN K16 [get_ports {cathode[2]}]
set_property PACKAGE_PIN R10 [get_ports {cathode[1]}]
set_property PACKAGE_PIN T10 [get_ports {cathode[0]}]
set_property PACKAGE_PIN J17 [get_ports a0]
set_property PACKAGE_PIN J18 [get_ports a1]
set_property PACKAGE_PIN D12 [get_ports audio_enable]

set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
set_property PACKAGE_PIN F5 [get_ports channelselect]
set_property PACKAGE_PIN H5 [get_ports microphone]
set_property PACKAGE_PIN J5 [get_ports pdm_clk_o]
set_property PACKAGE_PIN N17 [get_ports record]
set_property PACKAGE_PIN P17 [get_ports reset]
set_property PACKAGE_PIN L16 [get_ports switch1]
set_property PACKAGE_PIN A11 [get_ports audio_out]
set_property IOSTANDARD LVCMOS33 [get_ports a0]
set_property IOSTANDARD LVCMOS33 [get_ports a1]
set_property IOSTANDARD LVCMOS33 [get_ports audio_enable]
set_property IOSTANDARD LVCMOS33 [get_ports audio_out]
set_property IOSTANDARD LVCMOS33 [get_ports channelselect]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports microphone]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_clk_o]
set_property IOSTANDARD LVCMOS33 [get_ports play]
set_property IOSTANDARD LVCMOS33 [get_ports record]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports switch0]
set_property IOSTANDARD LVCMOS33 [get_ports switch1]


set_property PACKAGE_PIN E3 [get_ports clock]

create_clock -period 10.000 -name clock -waveform {0.000 5.000} -add [get_ports clock]

set_property PACKAGE_PIN J15 [get_ports switch0]

set_property PACKAGE_PIN M17 [get_ports play]
